# Generated by Django 4.0.6 on 2022-09-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Научные термины', 'verbose_name_plural': 'Научные термины'},
        ),
    ]
